name: Run Tests

on:
  workflow_dispatch:
    inputs:
      test_suite:
        description: 'Select Test Suite'
        required: true
        default: 'all'
        type: choice
        options:
          - unit
          - integration
          - e2e
          - all

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run selected test suite
      run: |
        echo "Running ${{ github.event.inputs.test_suite }} tests"
